# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sGrx1e1rXkYAj05-dlbvN5BaKGYZq_9a
"""

name = "shahzad"
rollno = 67



print("my name is : ".format(name))
print("my roll number is {}".format(rollno))